export interface Buyer {
    buyers_i_information_id? : number,
    buyers_name: string,
    contact_number: string,
    province?: string,
    municipality?: string,
    barangay?: string,
    purok?: string,
    zipcode?: number,
    civil_status?: string,
    sex?: string,
    birthdate?: Date,
    birthplace?: string,
    occupation?: string,
    company_name?: string,
    created_by?: number,
    otp: string,
}
